# fly.toml app configuration file generated for email-parser-for-pipedrive on 2025-07-30T11:48:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'email-parser-for-pipedrive'
primary_region = 'lhr'

[build]

[processes]
worker = "node index.js"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
